# Generated by Django 4.2 on 2023-04-21 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteweb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.CharField(max_length=50)),
                ('about_en', models.CharField(max_length=50, null=True)),
                ('about_fr', models.CharField(max_length=50, null=True)),
                ('about_es', models.CharField(max_length=50, null=True)),
                ('about_text', models.TextField()),
                ('about_text_en', models.TextField(null=True)),
                ('about_text_fr', models.TextField(null=True)),
                ('about_text_es', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(max_length=50)),
                ('contact_en', models.CharField(max_length=50, null=True)),
                ('contact_fr', models.CharField(max_length=50, null=True)),
                ('contact_es', models.CharField(max_length=50, null=True)),
                ('contact_text', models.TextField()),
                ('contact_text_en', models.TextField(null=True)),
                ('contact_text_fr', models.TextField(null=True)),
                ('contact_text_es', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=50)),
                ('header_en', models.CharField(max_length=50, null=True)),
                ('header_fr', models.CharField(max_length=50, null=True)),
                ('header_es', models.CharField(max_length=50, null=True)),
                ('header_text', models.TextField()),
                ('header_text_en', models.TextField(null=True)),
                ('header_text_fr', models.TextField(null=True)),
                ('header_text_es', models.TextField(null=True)),
                ('header_button', models.CharField(max_length=20)),
                ('header_button_en', models.CharField(max_length=20, null=True)),
                ('header_button_fr', models.CharField(max_length=20, null=True)),
                ('header_button_es', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
