# Generated by Django 4.2 on 2023-04-27 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteweb', '0002_about_contact_home'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firt_title', models.CharField(max_length=30)),
                ('firt_title_en', models.CharField(max_length=30, null=True)),
                ('firt_title_fr', models.CharField(max_length=30, null=True)),
                ('firt_title_es', models.CharField(max_length=30, null=True)),
                ('name', models.CharField(max_length=10)),
                ('name_en', models.CharField(max_length=10, null=True)),
                ('name_fr', models.CharField(max_length=10, null=True)),
                ('name_es', models.CharField(max_length=10, null=True)),
                ('last_name', models.CharField(max_length=10)),
                ('last_name_en', models.CharField(max_length=10, null=True)),
                ('last_name_fr', models.CharField(max_length=10, null=True)),
                ('last_name_es', models.CharField(max_length=10, null=True)),
                ('phone', models.CharField(max_length=10)),
                ('phone_en', models.CharField(max_length=10, null=True)),
                ('phone_fr', models.CharField(max_length=10, null=True)),
                ('phone_es', models.CharField(max_length=10, null=True)),
                ('mail', models.CharField(max_length=10)),
                ('mail_en', models.CharField(max_length=10, null=True)),
                ('mail_fr', models.CharField(max_length=10, null=True)),
                ('mail_es', models.CharField(max_length=10, null=True)),
                ('secound_title', models.CharField(max_length=30)),
                ('secound_title_en', models.CharField(max_length=30, null=True)),
                ('secound_title_fr', models.CharField(max_length=30, null=True)),
                ('secound_title_es', models.CharField(max_length=30, null=True)),
                ('address', models.CharField(max_length=10)),
                ('address_en', models.CharField(max_length=10, null=True)),
                ('address_fr', models.CharField(max_length=10, null=True)),
                ('address_es', models.CharField(max_length=10, null=True)),
                ('app', models.CharField(max_length=10)),
                ('app_en', models.CharField(max_length=10, null=True)),
                ('app_fr', models.CharField(max_length=10, null=True)),
                ('app_es', models.CharField(max_length=10, null=True)),
                ('city', models.CharField(max_length=10)),
                ('city_en', models.CharField(max_length=10, null=True)),
                ('city_fr', models.CharField(max_length=10, null=True)),
                ('city_es', models.CharField(max_length=10, null=True)),
                ('postal_code', models.CharField(max_length=10)),
                ('postal_code_en', models.CharField(max_length=10, null=True)),
                ('postal_code_fr', models.CharField(max_length=10, null=True)),
                ('postal_code_es', models.CharField(max_length=10, null=True)),
                ('tercer_title', models.CharField(max_length=30)),
                ('tercer_title_en', models.CharField(max_length=30, null=True)),
                ('tercer_title_fr', models.CharField(max_length=30, null=True)),
                ('tercer_title_es', models.CharField(max_length=30, null=True)),
                ('details', models.CharField(max_length=10)),
                ('details_en', models.CharField(max_length=10, null=True)),
                ('details_fr', models.CharField(max_length=10, null=True)),
                ('details_es', models.CharField(max_length=10, null=True)),
                ('submit', models.CharField(max_length=10)),
                ('submit_en', models.CharField(max_length=10, null=True)),
                ('submit_fr', models.CharField(max_length=10, null=True)),
                ('submit_es', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
