# Generated by Django 4.2 on 2023-04-28 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteweb', '0003_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='app',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='form',
            name='app_en',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='form',
            name='app_es',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='form',
            name='app_fr',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
