# Generated by Django 4.2 on 2023-04-28 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteweb', '0004_alter_form_app_alter_form_app_en_alter_form_app_es_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='postal_code',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='form',
            name='postal_code_en',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='form',
            name='postal_code_es',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='form',
            name='postal_code_fr',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
