# Generated by Django 4.2 on 2023-04-29 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteweb', '0006_alter_form_tercer_title_alter_form_tercer_title_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='header',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='home',
            name='header_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='header_es',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='header_fr',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
