# Generated by Django 4.2 on 2023-11-30 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteweb', '0007_alter_home_header_alter_home_header_en_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='home',
            old_name='header',
            new_name='header_decoration',
        ),
        migrations.RenameField(
            model_name='home',
            old_name='header_en',
            new_name='header_decoration_en',
        ),
        migrations.RenameField(
            model_name='home',
            old_name='header_es',
            new_name='header_decoration_es',
        ),
        migrations.RenameField(
            model_name='home',
            old_name='header_fr',
            new_name='header_decoration_fr',
        ),
        migrations.AddField(
            model_name='home',
            name='header_span',
            field=models.CharField(default='header_span_default', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='home',
            name='header_span_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='header_span_es',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='header_span_fr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='header_title',
            field=models.CharField(default='header_title_default', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='home',
            name='header_title_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='header_title_es',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='header_title_fr',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
