# Generated by Django 4.2 on 2023-11-30 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteweb', '0008_rename_header_home_header_decoration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='service_span',
            field=models.CharField(default='service_span_default', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='home',
            name='service_title',
            field=models.CharField(default='service_title_default', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='home',
            name='warranty_span',
            field=models.CharField(default='warranty_span_default', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='home',
            name='warranty_subtitle_estimate',
            field=models.CharField(default='warranty_subtitle_estimate_default', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='home',
            name='warranty_subtitle_warranty',
            field=models.CharField(default='warranty_subtitle_warranty_default', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='home',
            name='warranty_text_estimate',
            field=models.TextField(default='warranty_text_estimate_default'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='home',
            name='warranty_text_warranty',
            field=models.TextField(default='warranty_text_warranty_default'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='home',
            name='warranty_title',
            field=models.CharField(default='warranty_title_default', max_length=100),
            preserve_default=False,
        ),
    ]
