# Generated by Django 4.2 on 2023-11-30 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteweb', '0009_home_service_span_home_service_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='service_span_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='service_span_es',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='service_span_fr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='service_title_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='service_title_es',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='service_title_fr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='warranty_span_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='warranty_span_es',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='warranty_span_fr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='warranty_subtitle_estimate_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='warranty_subtitle_estimate_es',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='warranty_subtitle_estimate_fr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='warranty_subtitle_warranty_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='warranty_subtitle_warranty_es',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='warranty_subtitle_warranty_fr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='warranty_text_estimate_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='warranty_text_estimate_es',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='warranty_text_estimate_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='warranty_text_warranty_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='warranty_text_warranty_es',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='warranty_text_warranty_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='warranty_title_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='warranty_title_es',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='warranty_title_fr',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
