# Generated by Django 4.2 on 2023-11-30 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteweb', '0010_home_service_span_en_home_service_span_es_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='warranty_button',
            field=models.CharField(default='warranty button contact estimate', max_length=80),
        ),
        migrations.AddField(
            model_name='home',
            name='warranty_button_en',
            field=models.CharField(default='warranty button contact estimate', max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='warranty_button_es',
            field=models.CharField(default='warranty button contact estimate', max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='warranty_button_fr',
            field=models.CharField(default='warranty button contact estimate', max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='service_span',
            field=models.CharField(default='service title span', max_length=100),
        ),
        migrations.AlterField(
            model_name='home',
            name='service_span_en',
            field=models.CharField(default='service title span', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='service_span_es',
            field=models.CharField(default='service title span', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='service_span_fr',
            field=models.CharField(default='service title span', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='service_title',
            field=models.CharField(default='service title', max_length=100),
        ),
        migrations.AlterField(
            model_name='home',
            name='service_title_en',
            field=models.CharField(default='service title', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='service_title_es',
            field=models.CharField(default='service title', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='service_title_fr',
            field=models.CharField(default='service title', max_length=100, null=True),
        ),
    ]
