# Generated by Django 4.2 on 2023-12-01 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteweb', '0011_home_warranty_button_home_warranty_button_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='service',
            name='description_es',
        ),
        migrations.RemoveField(
            model_name='service',
            name='description_fr',
        ),
        migrations.RemoveField(
            model_name='service',
            name='name',
        ),
        migrations.RemoveField(
            model_name='service',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='service',
            name='name_es',
        ),
        migrations.RemoveField(
            model_name='service',
            name='name_fr',
        ),
        migrations.AddField(
            model_name='service',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='img/banner'),
        ),
        migrations.AddField(
            model_name='service',
            name='title',
            field=models.CharField(default='Service', max_length=255),
        ),
        migrations.AddField(
            model_name='service',
            name='title_en',
            field=models.CharField(default='Service', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='title_es',
            field=models.CharField(default='Service', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='title_fr',
            field=models.CharField(default='Service', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
