# Generated by Django 4.2 on 2023-12-01 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteweb', '0013_service_description_en_service_description_es_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='service_text',
            field=models.TextField(default='service text paragraph'),
        ),
        migrations.AddField(
            model_name='home',
            name='service_text_en',
            field=models.TextField(default='service text paragraph', null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='service_text_es',
            field=models.TextField(default='service text paragraph', null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='service_text_fr',
            field=models.TextField(default='service text paragraph', null=True),
        ),
    ]
