# Generated by Django 4.2 on 2023-12-02 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteweb', '0014_home_service_text_home_service_text_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='url',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
