# Generated by Django 4.2 on 2023-12-02 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteweb', '0015_service_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='button_detail',
            field=models.CharField(default='View details', max_length=18, verbose_name='View details button'),
        ),
        migrations.AddField(
            model_name='service',
            name='button_detail_en',
            field=models.CharField(default='View details', max_length=18, null=True, verbose_name='View details button'),
        ),
        migrations.AddField(
            model_name='service',
            name='button_detail_es',
            field=models.CharField(default='View details', max_length=18, null=True, verbose_name='View details button'),
        ),
        migrations.AddField(
            model_name='service',
            name='button_detail_fr',
            field=models.CharField(default='View details', max_length=18, null=True, verbose_name='View details button'),
        ),
    ]
