# Generated by Django 4.2 on 2023-12-02 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteweb', '0016_service_button_detail_service_button_detail_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Title Name', max_length=60)),
                ('subtitle', models.CharField(default='Text of Subtitle', max_length=100)),
                ('description', models.TextField(default='Descriptive text of this topic')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='img/thumbnail')),
            ],
        ),
    ]
