# Generated by Django 4.2 on 2023-12-02 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteweb', '0017_service_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_1',
            name='description_en',
            field=models.TextField(default='Descriptive text of this topic', null=True),
        ),
        migrations.AddField(
            model_name='service_1',
            name='description_es',
            field=models.TextField(default='Descriptive text of this topic', null=True),
        ),
        migrations.AddField(
            model_name='service_1',
            name='description_fr',
            field=models.TextField(default='Descriptive text of this topic', null=True),
        ),
        migrations.AddField(
            model_name='service_1',
            name='subtitle_en',
            field=models.CharField(default='Text of Subtitle', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='service_1',
            name='subtitle_es',
            field=models.CharField(default='Text of Subtitle', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='service_1',
            name='subtitle_fr',
            field=models.CharField(default='Text of Subtitle', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='service_1',
            name='title_en',
            field=models.CharField(default='Title Name', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='service_1',
            name='title_es',
            field=models.CharField(default='Title Name', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='service_1',
            name='title_fr',
            field=models.CharField(default='Title Name', max_length=60, null=True),
        ),
    ]
