# Generated by Django 4.2 on 2023-12-02 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteweb', '0020_repairservice'),
    ]

    operations = [
        migrations.CreateModel(
            name='GarageService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Title Name', max_length=60)),
                ('title_en', models.CharField(default='Title Name', max_length=60, null=True)),
                ('title_fr', models.CharField(default='Title Name', max_length=60, null=True)),
                ('title_es', models.CharField(default='Title Name', max_length=60, null=True)),
                ('subtitle', models.CharField(default='Text of Subtitle', max_length=100)),
                ('subtitle_en', models.CharField(default='Text of Subtitle', max_length=100, null=True)),
                ('subtitle_fr', models.CharField(default='Text of Subtitle', max_length=100, null=True)),
                ('subtitle_es', models.CharField(default='Text of Subtitle', max_length=100, null=True)),
                ('description', models.TextField(default='Descriptive text of this topic')),
                ('description_en', models.TextField(default='Descriptive text of this topic', null=True)),
                ('description_fr', models.TextField(default='Descriptive text of this topic', null=True)),
                ('description_es', models.TextField(default='Descriptive text of this topic', null=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='img/thumbnail')),
            ],
        ),
    ]
