# Generated by Django 4.2 on 2023-12-03 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteweb', '0023_alter_cascadesservice_subtitle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='submit',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='form',
            name='submit_en',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='form',
            name='submit_es',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='form',
            name='submit_fr',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
