# Generated by Django 4.2 on 2023-12-07 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteweb', '0025_testimonial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='client_charge',
            field=models.CharField(default='Client', max_length=50),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='client_charge_en',
            field=models.CharField(default='Client', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='client_charge_es',
            field=models.CharField(default='Client', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='client_charge_fr',
            field=models.CharField(default='Client', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='testimonial',
            field=models.TextField(max_length=562),
        ),
    ]
