# Generated by Django 4.2 on 2023-12-08 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteweb', '0026_alter_testimonial_client_charge_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='banner'),
        ),
    ]
