# Generated by Django 4.2 on 2023-12-09 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteweb', '0027_alter_service_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='gallery')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
