# Generated by Django 4.2 on 2023-12-09 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteweb', '0028_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gallery',
            name='width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
