# Generated by Django 4.2 on 2023-12-09 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteweb', '0029_gallery_height_gallery_width'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='height',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='width',
        ),
    ]
