# Generated by Django 4.2 on 2023-12-11 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteweb', '0032_bannerpage_banner_en_bannerpage_banner_es_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BannerPage',
        ),
    ]
