# Generated by Django 4.2 on 2023-12-11 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteweb', '0033_delete_bannerpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ImageField(upload_to='banner')),
            ],
        ),
    ]
