# Generated by Django 4.2 on 2023-12-11 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteweb', '0035_remove_bannerpage_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerpage',
            name='banner',
            field=models.ImageField(default='Required', upload_to='banner'),
        ),
        migrations.AddField(
            model_name='bannerpage',
            name='subtitle',
            field=models.TextField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='bannerpage',
            name='subtitle_en',
            field=models.TextField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='bannerpage',
            name='subtitle_es',
            field=models.TextField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='bannerpage',
            name='subtitle_fr',
            field=models.TextField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='bannerpage',
            name='title',
            field=models.CharField(default='Title Name', max_length=50),
        ),
        migrations.AddField(
            model_name='bannerpage',
            name='title_en',
            field=models.CharField(default='Title Name', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bannerpage',
            name='title_es',
            field=models.CharField(default='Title Name', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bannerpage',
            name='title_fr',
            field=models.CharField(default='Title Name', max_length=50, null=True),
        ),
    ]
