# Generated by Django 4.2 on 2023-12-11 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteweb', '0036_bannerpage_banner_bannerpage_subtitle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerpage',
            name='banner',
            field=models.ImageField(blank=True, upload_to='banner'),
        ),
    ]
