# Generated by Django 4.2 on 2023-12-12 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteweb', '0037_alter_bannerpage_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerpage',
            name='identificador',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
