# Generated by Django 4.2 on 2023-12-12 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteweb', '0038_bannerpage_identificador'),
    ]

    operations = [
        migrations.AddField(
            model_name='cascadesservice',
            name='identificador',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='concreteservice',
            name='identificador',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='garageservice',
            name='identificador',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='lightingservice',
            name='identificador',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='pavingservice',
            name='identificador',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='plantingservice',
            name='identificador',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='platformservice',
            name='identificador',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='poolservice',
            name='identificador',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='repairservice',
            name='identificador',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='wallsservice',
            name='identificador',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
