# Generated by Django 4.2 on 2023-12-12 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteweb', '0039_cascadesservice_identificador_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='identificador',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
