# Generated by Django 4.2 on 2023-12-12 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteweb', '0042_about_long_text_about_long_text_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='text',
        ),
        migrations.RemoveField(
            model_name='about',
            name='text_en',
        ),
        migrations.RemoveField(
            model_name='about',
            name='text_es',
        ),
        migrations.RemoveField(
            model_name='about',
            name='text_fr',
        ),
        migrations.AddField(
            model_name='about',
            name='short_text',
            field=models.TextField(default='A small paragraph'),
        ),
        migrations.AddField(
            model_name='about',
            name='short_text_en',
            field=models.TextField(default='A small paragraph', null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='short_text_es',
            field=models.TextField(default='A small paragraph', null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='short_text_fr',
            field=models.TextField(default='A small paragraph', null=True),
        ),
    ]
