# Generated by Django 4.2 on 2023-12-14 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteweb', '0044_alter_about_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='background',
            field=models.ImageField(null=True, upload_to='home'),
        ),
    ]
