# Generated by Django 4.2 on 2023-12-14 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteweb', '0045_home_background'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='banner',
            field=models.ImageField(null=True, upload_to='banner'),
        ),
    ]
