# Generated by Django 4.2 on 2023-12-14 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteweb', '0046_alter_service_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='testimonials_title',
            field=models.CharField(default='Testimonials', max_length=50),
        ),
    ]
