# Generated by Django 4.2 on 2023-12-14 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteweb', '0049_rename_tercer_title_form_third_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='contact_en',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='contact_es',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='contact_fr',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='contact_text',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='contact_text_en',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='contact_text_es',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='contact_text_fr',
        ),
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='contact',
            name='email_title',
            field=models.CharField(default='Email', max_length=20),
        ),
        migrations.AddField(
            model_name='contact',
            name='email_title_en',
            field=models.CharField(default='Email', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='email_title_es',
            field=models.CharField(default='Email', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='email_title_fr',
            field=models.CharField(default='Email', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='info_form',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='contact',
            name='info_form_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='info_form_es',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='info_form_fr',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='contact',
            name='phone_title',
            field=models.CharField(default='Phone', max_length=20),
        ),
        migrations.AddField(
            model_name='contact',
            name='phone_title_en',
            field=models.CharField(default='Phone', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='phone_title_es',
            field=models.CharField(default='Phone', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='phone_title_fr',
            field=models.CharField(default='Phone', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='text_direct_contact',
            field=models.CharField(default='Contact Us Directly', max_length=50),
        ),
        migrations.AddField(
            model_name='contact',
            name='text_direct_contact_en',
            field=models.CharField(default='Contact Us Directly', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='text_direct_contact_es',
            field=models.CharField(default='Contact Us Directly', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='text_direct_contact_fr',
            field=models.CharField(default='Contact Us Directly', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='text_social_networks',
            field=models.CharField(default='Connect with us on social networks', max_length=50),
        ),
        migrations.AddField(
            model_name='contact',
            name='text_social_networks_en',
            field=models.CharField(default='Connect with us on social networks', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='text_social_networks_es',
            field=models.CharField(default='Connect with us on social networks', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='text_social_networks_fr',
            field=models.CharField(default='Connect with us on social networks', max_length=50, null=True),
        ),
    ]
