# Generated by Django 4.2 on 2023-12-14 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteweb', '0050_remove_contact_contact_remove_contact_contact_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='info_form',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='contact',
            name='info_form_en',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='info_form_es',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='info_form_fr',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
