# Generated by Django 4.2 on 2023-12-14 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteweb', '0051_alter_contact_info_form_alter_contact_info_form_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='link_facebook',
            field=models.URLField(default='https://www.facebook.com/'),
        ),
        migrations.AddField(
            model_name='contact',
            name='link_instagram',
            field=models.URLField(default='https://www.instagram.com/'),
        ),
    ]
