# Generated by Django 4.2 on 2023-12-19 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteweb', '0053_alter_cascadesservice_thumbnail_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cascadesservice',
            name='identificador',
        ),
        migrations.RemoveField(
            model_name='concreteservice',
            name='identificador',
        ),
        migrations.RemoveField(
            model_name='garageservice',
            name='identificador',
        ),
        migrations.RemoveField(
            model_name='lightingservice',
            name='identificador',
        ),
        migrations.RemoveField(
            model_name='pavingservice',
            name='identificador',
        ),
        migrations.RemoveField(
            model_name='plantingservice',
            name='identificador',
        ),
        migrations.RemoveField(
            model_name='platformservice',
            name='identificador',
        ),
        migrations.RemoveField(
            model_name='poolservice',
            name='identificador',
        ),
        migrations.RemoveField(
            model_name='repairservice',
            name='identificador',
        ),
        migrations.RemoveField(
            model_name='wallsservice',
            name='identificador',
        ),
    ]
