# Generated by Django 4.2 on 2023-12-26 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteweb', '0054_remove_cascadesservice_identificador_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='Landscaping expert in downtown Quebec City', max_length=60)),
                ('text_locations', models.TextField()),
            ],
        ),
    ]
