# Generated by Django 4.2 on 2023-12-26 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteweb', '0055_servicelocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicelocation',
            name='text_en',
            field=models.CharField(default='Landscaping expert in downtown Quebec City', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='servicelocation',
            name='text_es',
            field=models.CharField(default='Landscaping expert in downtown Quebec City', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='servicelocation',
            name='text_fr',
            field=models.CharField(default='Landscaping expert in downtown Quebec City', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='servicelocation',
            name='text_locations_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='servicelocation',
            name='text_locations_es',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='servicelocation',
            name='text_locations_fr',
            field=models.TextField(null=True),
        ),
    ]
