# Generated by Django 4.2 on 2024-01-05 19:12

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteweb', '0056_servicelocation_text_en_servicelocation_text_es_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='images',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='gallery'),
        ),
    ]
