# Generated by Django 4.2 on 2024-01-07 03:03

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteweb', '0057_alter_gallery_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='banner',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='banner'),
        ),
    ]
