# Generated by Django 4.2 on 2024-01-07 04:51

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteweb', '0059_alter_cascadesservice_thumbnail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerpage',
            name='banner',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='banner'),
        ),
    ]
