# Generated by Django 4.2 on 2024-01-16 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteweb', '0060_alter_bannerpage_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerpage',
            name='subtitle',
            field=models.TextField(blank=True, max_length=210),
        ),
        migrations.AlterField(
            model_name='bannerpage',
            name='subtitle_en',
            field=models.TextField(blank=True, max_length=210, null=True),
        ),
        migrations.AlterField(
            model_name='bannerpage',
            name='subtitle_es',
            field=models.TextField(blank=True, max_length=210, null=True),
        ),
        migrations.AlterField(
            model_name='bannerpage',
            name='subtitle_fr',
            field=models.TextField(blank=True, max_length=210, null=True),
        ),
    ]
